apiVersion: apps/v1
kind: Deployment
metadata:
 name: deploy
spec:
 replicas: 1
 selector:
  matchLabels:
   name: deploy
 template:
  metadata:
   labels:
    name: deploy
  spec:
   containers:
   - name: cont01
     image: shreya0666/sample-project1
     ports:
     - containerPort: 8080
   
   
